### ISSUE TITLE
在训练过程中的问题

### ISSUE THREAD

**Issue by heikeyuhuajia** [KyanChen/STT#15]
您好，我用了我们自己的数据集训练，在第一个epoch的时候就出现了下面的问题：
`warning: num_class is not equal to 1000, which will cause some parameters to fail to load!
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /home/wyuan/.cache/torch/hub/checkpoints/resnet50-19c8e357.pth
100%|███████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [00:07<00:00, 13.6MB/s]
load resnet model...
load checkpoint from /home/wyuan/cyberpunk/BuildingExtraction/WHU_ckpt_latest.pt
Use GPUs: range(0, 2)
train: 0/300 1/35 loss: 1.9584
train: 0/300 21/35 loss: 0.2031
Traceback (most recent call last):
  File "Train.py", line 111, in <module>
    logits, att_branch_output = model(img_batch)
  File "/home/wyuan/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wyuan/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/wyuan/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/wyuan/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/wyuan/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
ValueError: Caught ValueError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/wyuan/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/wyuan/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wyuan/cyberpunk/BuildingExtraction/STTNet.py", line 232, in forward
    prob_c_map = self.get_c_probability(x_reduced_channel)  # B C 1 1
  File "/home/wyuan/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wyuan/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/wyuan/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wyuan/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/home/wyuan/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/functional.py", line 2419, in batch_norm
    _verify_batch_size(input.size())
  File "/home/wyuan/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/functional.py", line 2387, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 8, 1, 1])`  这是怎么回事呢？

**Comment by KyanChen** [comment]
应该是BS=1，“got input size torch.Size([1, 8, 1, 1])“，在DP的时候没办法进行BN运算。出现这歌问题的原因是你的训练数据集图片数目/显卡数量 余下来了1张。解决方法：调整显卡数量；或者更改batchsize；或者train_dataloader中设置drop_last=True；或者多复制几张图使得余数不为1。

**Comment by heikeyuhuajia** [comment]
感谢您的回复，根据您的指导已经跑起来了，谢谢您！
